# Generated by Django 4.0.1 on 2022-01-18 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        ('crew', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directors', to='movies.country'),
        ),
        migrations.AddField(
            model_name='actor',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actors', to='movies.country'),
        ),
    ]
